-- Table: public.StoredProcedureRegistry
 
-- DROP TABLE IF EXISTS public."StoredProcedureRegistry";
 
CREATE TABLE IF NOT EXISTS public."StoredProcedureRegistry"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ProcedureName" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "DisplayName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying(500) COLLATE pg_catalog."default",
    "ClientId" integer,
    "Category" character varying(50) COLLATE pg_catalog."default",
    "IsActive" boolean NOT NULL,
    "RequiresAuth" boolean NOT NULL,
    "AllowedRoles" text COLLATE pg_catalog."default" NOT NULL DEFAULT '[]'::text,
    "CacheDurationSeconds" integer,
    "DefaultPageSize" integer NOT NULL,
    "MaxPageSize" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" integer,
    "UpdatedBy" integer,
    "DatabaseName" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "PK_StoredProcedureRegistry" PRIMARY KEY ("Id")
)
 
TABLESPACE pg_default;
 
ALTER TABLE IF EXISTS public."StoredProcedureRegistry"
    OWNER to postgres;
 
COMMENT ON COLUMN public."StoredProcedureRegistry"."DatabaseName"
    IS 'Database identifier for routing procedure calls. Maps to connection string names in appsettings.json. If null, uses DefaultConnection.';
-- Index: IX_StoredProcedureRegistry_Category_IsActive
 
-- DROP INDEX IF EXISTS public."IX_StoredProcedureRegistry_Category_IsActive";
 
CREATE INDEX IF NOT EXISTS "IX_StoredProcedureRegistry_Category_IsActive"
    ON public."StoredProcedureRegistry" USING btree
    ("Category" COLLATE pg_catalog."default" ASC NULLS LAST, "IsActive" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: IX_StoredProcedureRegistry_ProcedureName
 
-- DROP INDEX IF EXISTS public."IX_StoredProcedureRegistry_ProcedureName";
 
CREATE UNIQUE INDEX IF NOT EXISTS "IX_StoredProcedureRegistry_ProcedureName"
    ON public."StoredProcedureRegistry" USING btree
    ("ProcedureName" COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: idx_storedprocedureregistry_databasename
 
-- DROP INDEX IF EXISTS public.idx_storedprocedureregistry_databasename;
 
CREATE INDEX IF NOT EXISTS idx_storedprocedureregistry_databasename
    ON public."StoredProcedureRegistry" USING btree
    ("DatabaseName" COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default
    WHERE "DatabaseName" IS NOT NULL;